namespace: websimple
name: wordpress
version: 1.0.0
readme: README.md
authors:
  - Pascal Martineau <pascal@lewebsimple.ca>
description: Shared Ansible roles and playbooks for WordPress projects.
license:
  - MIT
repository: https://github.com/lewebsimple/ansible-wordpress
