---
- name: Sync uploads from remote to local
  ansible.builtin.synchronize:
    src: "{{ remote_path }}/wp-content/uploads"
    dest: "{{ local_path }}/wp-content/uploads"
    mode: "{{ sync_mode }}"
    rsync_opts:
      - "--rsh=ssh -p {{ remote_port }}"
