---
- name: Sync uploads from remote to local
  ansible.builtin.synchronize:
    src: "{{ remote_path }}/wp-content/uploads"
    dest: "{{ local_path }}/wp-content/uploads"
    mode: "{{ sync_mode }}"
    rsync_opts:
      - "--rsh=ssh -p {{ remote_port }}"
  when: sync_mode == "pull"

- name: Sync uploads from local to remote
  ansible.builtin.synchronize:
    src: "{{ local_path }}/wp-content/uploads"
    dest: "{{ remote_path }}/wp-content/uploads"
    mode: "{{ sync_mode }}"
    rsync_opts:
      - "--rsh=ssh -p {{ remote_port }}"
  when: sync_mode == "push"
